type User {
	id: ID
	name: String
	avatar: String
	email: String
}

# update the Query type schema to allow users to accept the first and after arguments
type Query {
	users(first: Int, after: Int): [User]
}
